### ISSUE TITLE
想了解数据所指的意义

### ISSUE THREAD

**Issue by bravejpg** [orion-orion/AirPassengerAnalysis#3]
运行后发现共有epoch,loss train acc,，test acc，train f1，test f1，train auc，test auc这些数据。所以想问一下loss指的是损失函数、acc指的是准确率、f1指的是f1 score吗？auc取值是0.5~1，为什么我的auc刚开始跑出来会小于0.5？

**Comment by orion-orion** [comment]
哈哈突然发现这个上古issue还没回复。你对数据评价指标的理解是正确的，这里train AUC < 0.5 表示方向预测，也就是说模型沒有学好，可以多等待几轮哦~
